---
- hosts: all
  become: yes
  tasks: 
  - name : i want to install git on ubuntu nodes
    apt: 
      name: git
      state: present


  - name: install tree
    apt:
      name: tree
      state: present

  - name: install wget on ubuntu nodes
    apt:
       name: wget
       state: present
  