---
- hosts: 172.31.30.129 
  become: yes
  tasks:
  - include_tasks: myfile.yaml
  - name: i want to install webserver on ansible node
    apt:
      name: apache2
      state: present
  - name: i want copy myindex file into ansible node side
    templates:
        src: myindex.j2
        dest: /var/www/html/index.html

