---
- hosts:
  become:
  vars: 
    myvar1: git
    myvar2: tree
    myvar3: weget
  tasks: 
  - name: install tree
    apt:
      name:"{{myvar1}}"  
  - name: i want to display myvar1
    debug: 
      msg: "{{myvar1}}"
      